/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.generator;

import com.google.common.collect.Iterators;
import dk.sdu.mmmi.mdsd.math.Div;
import dk.sdu.mmmi.mdsd.math.Expression;
import dk.sdu.mmmi.mdsd.math.Let;
import dk.sdu.mmmi.mdsd.math.MathExp;
import dk.sdu.mmmi.mdsd.math.Minus;
import dk.sdu.mmmi.mdsd.math.Mult;
import dk.sdu.mmmi.mdsd.math.Num;
import dk.sdu.mmmi.mdsd.math.Plus;
import dk.sdu.mmmi.mdsd.math.Var;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MathGenerator extends AbstractGenerator {
  private static Map<String, Integer> variables = new HashMap<String, Integer>();
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final Iterator<MathExp> math = Iterators.<MathExp>filter(resource.getAllContents(), MathExp.class);
    final List<MathExp> list = IteratorExtensions.<MathExp>toList(math);
    for (final MathExp exp : list) {
      MathGenerator.compute(exp);
    }
    this.displayPanel(MathGenerator.variables);
  }
  
  public static Map<String, Integer> compute(final MathExp math) {
    MathGenerator.variables.put(math.getName(), Integer.valueOf(MathGenerator.computeExp(math.getExp(), MathGenerator.variables)));
    return MathGenerator.variables;
  }
  
  public static int computeExp(final Expression exp, final Map<String, Integer> map) {
    Integer _switchResult = null;
    boolean _matched = false;
    if (exp instanceof Plus) {
      _matched=true;
      int _computeExp = MathGenerator.computeExp(((Plus)exp).getLeft(), map);
      int _computeExp_1 = MathGenerator.computeExp(((Plus)exp).getRight(), map);
      _switchResult = Integer.valueOf((_computeExp + _computeExp_1));
    }
    if (!_matched) {
      if (exp instanceof Minus) {
        _matched=true;
        int _computeExp = MathGenerator.computeExp(((Minus)exp).getLeft(), map);
        int _computeExp_1 = MathGenerator.computeExp(((Minus)exp).getRight(), map);
        _switchResult = Integer.valueOf((_computeExp - _computeExp_1));
      }
    }
    if (!_matched) {
      if (exp instanceof Mult) {
        _matched=true;
        int _computeExp = MathGenerator.computeExp(((Mult)exp).getLeft(), map);
        int _computeExp_1 = MathGenerator.computeExp(((Mult)exp).getRight(), map);
        _switchResult = Integer.valueOf((_computeExp * _computeExp_1));
      }
    }
    if (!_matched) {
      if (exp instanceof Div) {
        _matched=true;
        int _computeExp = MathGenerator.computeExp(((Div)exp).getLeft(), map);
        int _computeExp_1 = MathGenerator.computeExp(((Div)exp).getRight(), map);
        _switchResult = Integer.valueOf((_computeExp / _computeExp_1));
      }
    }
    if (!_matched) {
      if (exp instanceof Var) {
        _matched=true;
        _switchResult = map.get(((Var)exp).getRef().getName());
      }
    }
    if (!_matched) {
      if (exp instanceof Num) {
        _matched=true;
        _switchResult = Integer.valueOf(((Num)exp).getValue());
      }
    }
    if (!_matched) {
      if (exp instanceof Let) {
        _matched=true;
        _switchResult = Integer.valueOf(MathGenerator.computeExp(((Let)exp).getBody(), MathGenerator.bind(map, ((Let)exp).getId(), MathGenerator.computeExp(((Let)exp).getBinding(), map))));
      }
    }
    if (!_matched) {
      throw new Error("Expression is not accepted");
    }
    return (_switchResult).intValue();
  }
  
  public static Map<String, Integer> bind(final Map<String, Integer> map1, final String name, final int value) {
    Map<String, Integer> _xblockexpression = null;
    {
      MathGenerator.variables.put(name, Integer.valueOf(value));
      _xblockexpression = MathGenerator.variables;
    }
    return _xblockexpression;
  }
  
  public void displayPanel(final Map<String, Integer> result) {
    String resultString = "";
    Set<Map.Entry<String, Integer>> _entrySet = result.entrySet();
    for (final Map.Entry<String, Integer> entry : _entrySet) {
      String _resultString = resultString;
      String _key = entry.getKey();
      String _plus = ("var " + _key);
      String _plus_1 = (_plus + " = ");
      Integer _value = entry.getValue();
      String _plus_2 = (_plus_1 + _value);
      String _plus_3 = (_plus_2 + "\n");
      resultString = (_resultString + _plus_3);
    }
    JOptionPane.showMessageDialog(null, resultString, "Math Language", JOptionPane.INFORMATION_MESSAGE);
  }
}
